### ISSUE TITLE
Don't go to fight with just 2 heroines.

### ISSUE THREAD

**Issue by awmbaptista** [dbox-dev/luna-rush-auto-click#3]
Even though I set it to only take 2 heroines to fight, it pushes 3.

config.yaml->
Set heros per fight default 3
hero_per_fight: 2

[logger.log](https://github.com/dbox-dev/luna-rush-auto-click/files/8239120/logger.log)

**Comment by dbox-dev** [comment]
> 

Fixed in version 2.2.1
