### ISSUE TITLE
Issue on 3.0.1

### ISSUE THREAD

**Issue by awmbaptista** [dbox-dev/luna-rush-auto-click#8]
![image](https://user-images.githubusercontent.com/86299415/163725531-4269212e-d4d6-493d-9bea-180b94cd914e.png)

Im getting this error on new version.

**Comment by dbox-dev** [comment]
> ![image](https://user-images.githubusercontent.com/86299415/163725531-4269212e-d4d6-493d-9bea-180b94cd914e.png)
> 
> Im getting this error on new version.

Please change your team config from array to map more see in wiki.

**Comment by awmbaptista** [comment]
> > ![image](https://user-images.githubusercontent.com/86299415/163725531-4269212e-d4d6-493d-9bea-180b94cd914e.png)
> > Im getting this error on new version.
> 
> Please change your team config from array to map more see in wiki.

But i dont use teams and error occours.

![image](https://user-images.githubusercontent.com/86299415/164005908-856c17c1-828f-4ef6-a689-23620c0e2f02.png)

**Comment by dbox-dev** [comment]
Already fixed in v3.0.3

**Comment by awmbaptista** [comment]
Solved!
